language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
  - 0.4
notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Digits"); Pkg.test("Digits"; coverage=true)'
  
after_success:
- julia -e 'cd(Pkg.dir("Digits")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
